AM-2841: Add jurisdiction filter to system user hearings role (sscs & private law)
hmcts/am-role-assignment-service pull request #1924
Opened 2023-06-27 14:59 UTC by tomxelliott

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/AM-2841

### Change description ###
Add jurisdiction filter to system user hearings role (sscs & private law)

2023-06-28 10:12 UTC, mattnayler requested changes

2023-06-28 10:12 UTC, mattnayler commented on src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java
> +        "hearing-viewer,SYSTEM,PRIVATELAW,Benefit"
For read-ability the test Jurisdiction and Case Type should probably match up: e.g. 
* PRIVATELAW => PRLAPPS
* SSCS => Benefit
i.e. the only reason in the test to expect failure should be the mis-matched process and jurisdiction: not the mis-matched case-type  (I know this is not a rule enforced here but it is in many other rule/config scenarios).

2023-06-28 10:12 UTC, mattnayler commented on src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java
> +        "hearing-viewer,SYSTEM,SSCS,PRLAPPS"
For read-ability the test Jurisdiction and Case Type should probably match up: e.g. 
* PRIVATELAW => PRLAPPS
* SSCS => Benefit
i.e. the only reason in the test to expect failure should be the mis-matched process and jurisdiction: not the mis-matched case-type  (I know this is not a rule enforced here but it is in many other rule/config scenarios).

2023-06-28 13:07 UTC, mattnayler commented on src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java
> +        "hearing-viewer,SYSTEM,PRIVATELAW,Benefit"
Resolved in 14c0ad52b5d834d1ff2b0bc8584bdb5ad5cef610

2023-06-28 13:07 UTC, mattnayler commented on src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java
> +        "hearing-viewer,SYSTEM,SSCS,PRLAPPS"
Resolved in 14c0ad52b5d834d1ff2b0bc8584bdb5ad5cef610

2023-06-28 13:07 UTC, mattnayler approved these changes

2023-07-05 13:57 UTC, abul-syed approved these changes

2023-07-05 14:38 UTC, merged