AM-2848: Retire obsolete controllers and associated tests after review
hmcts/am-role-assignment-service pull request #1927
Opened 2023-06-29 13:24 UTC by tomxelliott

### JIRA link (if applicable) ###
Retire obsolete controllers and associated tests after review

### Change description ###
https://tools.hmcts.net/jira/browse/AM-2848

2023-07-03 12:26 UTC, prashanthkumarnb approved these changes

2023-08-02 09:50 UTC, mattnayler requested changes

2023-08-02 09:50 UTC, mattnayler commented on src/integrationTest/java/uk/gov/hmcts/reform/roleassignment/data/RequestEntityIntegrationTest.java
> +    private static final Logger logger = LoggerFactory.getLogger(SwaggerRedirectControllerIntegrationTest.class);
Should this not be the class name?  either update or switch out for `@slf4j`.

2023-08-02 09:50 UTC, mattnayler commented on src/test/java/uk/gov/hmcts/reform/roleassignment/controller/advice/RoleAssignmentControllerAdviceTest.java
> +    private transient SwaggerRedirectController swaggerRedirectController = new SwaggerRedirectController();
Is this used in this test class?

2023-08-02 13:02 UTC, mattnayler commented on src/test/java/uk/gov/hmcts/reform/roleassignment/controller/advice/RoleAssignmentControllerAdviceTest.java
> +    private transient SwaggerRedirectController swaggerRedirectController = new SwaggerRedirectController();
Resolved in 2420705e085470515d9dcae8fab4e93dd9c97c2b.

2023-08-02 13:05 UTC, mattnayler approved these changes

2023-08-02 14:53 UTC, prashanthkumarnb approved these changes

2023-08-02 15:11 UTC, merged