AM-2861: Add caseworker-privatelaw-cafcass-cymru to role config
hmcts/am-role-assignment-service pull request #1936
Opened 2023-07-11 11:57 UTC by tomxelliott

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/AM-2861

### Change description ###
Add caseworker-privatelaw-cafcass-cymru to role config

2023-07-18 09:50 UTC, prashanthkumarnb approved these changes

2023-07-20 10:42 UTC, mattnayler requested changes

2023-07-20 10:42 UTC, mattnayler commented on src/main/resources/roleconfig/role_common.json
> +    "name": "caseworker-privatelaw-externaluser-viewonly",
Can we add unit tests to `src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java` as we do for other `OTHER_GOV_DEPT` roles such as [dwp, hmrc](https://github.com/hmcts/am-role-assignment-service/blob/50abff261fc17eabba78973dbb3b8daa4dd98320/src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/drools/AllServicesOrgRoleTest.java#L424-L425).

2023-07-20 10:55 UTC, mattnayler commented on src/main/resources/roleconfig/role_common.json
> +    "name": "caseworker-privatelaw-externaluser-viewonly",
Also add `listed-hearing-viewer` for PRIVATELAW to unit tests.

2023-07-20 14:19 UTC, mattnayler commented on src/main/resources/roleconfig/role_common.json
> +    "name": "caseworker-privatelaw-externaluser-viewonly",
Resolved in 37e10b1b96b9927511c31f2457353c826ca1c756

2023-07-20 14:20 UTC, mattnayler approved these changes
LGTM

2023-07-21 09:23 UTC, prashanthkumarnb approved these changes

2023-07-27 15:43 UTC, merged