DTSAM-492 Decommission Launch Darkly
hmcts/am-role-assignment-service pull request #2334
Opened 2024-09-12 12:09 UTC by mikebrownccd

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DTSAM-492

### Change description ###
Decommission Launch Darkly

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2025-02-06 15:57 UTC, mattnayler requested changes

2025-02-06 15:57 UTC, mattnayler commented on src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ValidationModelServiceTest.java
> +        when(environmentConfiguration.getEnvironment()).thenReturn("pr");
Verify behaviour change with environment change

2025-02-10 11:58 UTC, mattnayler commented on src/functionalTest/java/uk/gov/hmcts/reform/roleassignment/befta/RasDefaultMultiSourceFeatureToggleService.java
>          toggleable.getSourceTagNames().stream().filter(tag -> tag.contains(LAUNCH_DARKLY_FLAG)).forEach(tag -> {
Resolved in 80f585afd3f19a459541aeabe5a6486e4f8b299b.

2025-02-10 11:59 UTC, mattnayler commented on src/main/java/uk/gov/hmcts/reform/roleassignment/config/EnvironmentConfiguration.java
> +        if (StringUtils.isNotEmpty(rasEnvironment)) {
Resolved in 80f585afd3f19a459541aeabe5a6486e4f8b299b.

2025-02-10 12:00 UTC, mattnayler commented on src/main/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/PersistenceService.java
> +            envName = System.getenv("RAS_ENV");
Resolved in 80f585afd3f19a459541aeabe5a6486e4f8b299b.

2025-02-10 12:03 UTC, mattnayler commented on src/main/resources/application.yaml
> +  environment: ${RAS_ENV:}
Resolved in 80f585afd3f19a459541aeabe5a6486e4f8b299b.

2025-02-10 12:04 UTC, mattnayler commented on src/test/java/uk/gov/hmcts/reform/roleassignment/domain/service/common/ValidationModelServiceTest.java
> +        when(environmentConfiguration.getEnvironment()).thenReturn("pr");
Resolved in 80f585afd3f19a459541aeabe5a6486e4f8b299b.

2025-02-24 11:42 UTC, mattnayler commented on charts/am-role-assignment-service/values.yaml
> +    TESTING_SUPPORT_ENABLED: false
Flux PR has been created for AAT: see hmcts/cnp-flux-config#36954.

2025-02-26 12:21 UTC, prashanthnerligeb submitted a review, later dismissed
LGTM

2025-02-26 12:56 UTC, SabinaHMCTS submitted a review, later dismissed

2025-04-14 14:57 UTC, prashanthnerligeb approved these changes
LGTM

2025-04-14 15:06 UTC, merged