DTSAM-572 Audit use of case-allocator rules for CCD case-roles
hmcts/am-role-assignment-service pull request #2365
Opened 2024-10-25 15:03 UTC by mikebrownccd

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DTSAM-572

### Change description ###
DTSAM-572 Audit use of case-allocator rules for CCD case-roles

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-11-05 17:07 UTC, abul-syed requested changes
nice PR, 1 minor suggestion

2024-11-05 17:07 UTC, abul-syed commented on src/main/resources/validationrules/core/case-allocator-global.drl
> +      logInfoMsg("Rule : case_allocator_approve_create_case_role_all_wa_services" +
```suggestion
      logInfoMsg("Rule : case_allocator_approve_delete_case_role_all_wa_services" +
```

2024-11-05 17:33 UTC, mikebrownccd commented on src/main/resources/validationrules/core/case-allocator-global.drl
> +      logInfoMsg("Rule : case_allocator_approve_create_case_role_all_wa_services" +
updated

2024-11-05 17:34 UTC, abul-syed submitted a review, later dismissed
lgtm

2024-11-13 09:07 UTC, mattnayler submitted a review, later dismissed

2024-11-19 11:37 UTC, mattnayler approved these changes
RE-approved after base branch change.

2024-11-19 11:41 UTC, abul-syed approved these changes
lgtm

2024-11-19 11:46 UTC, merged